name: cms_maahadtahfizaddin
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  google_fonts: ^4.0.4
  lottie: ^2.3.2
  fluttertoast: ^8.2.1
  font_awesome_flutter: ^10.4.0
  #LIBRARY ----------------------------------------------------------

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  shimmer: ^2.0.0
  animate_do: ^3.0.2
  path_provider: ^2.0.11
  dio: ^5.1.2
  
  cached_network_image: ^3.2.2
  dio_cache_interceptor: ^3.3.1
  pull_to_refresh: ^2.0.0
  badges: ^3.1.1
  slide_digital_clock: ^1.0.3
  url_launcher: ^6.1.10
  #  syncfusion_flutter_calendar: ^20.2.49
  table_calendar: ^3.0.7
  flutter_advanced_drawer: ^1.3.2
  pretty_dio_logger: ^1.1.1
  permission_handler: ^10.1.0
  flutter_polyline_points: ^1.0.0
  geolocator: ^9.0.2
  location: ^4.4.0
  flutter_typeahead: ^4.1.1
  flutter_local_notifications: ^14.0.0+2
  flutter_native_timezone: ^2.0.0
  image: ^4.0.17
  device_info_plus: ^9.0.0
  line_icons: ^2.0.1
  flutter_keyboard_visibility: ^5.4.0
  carousel_slider: ^4.2.1
  page_view_dot_indicator: ^2.1.0
  flutter_file_downloader: ^1.1.0+1
  image_picker: ^0.8.7+1
  camera: ^0.10.4
  realm: ^1.2.0

  #FIREBASE ------------------------------
  firebase_core: ^2.12.0
  firebase_messaging: ^14.6.0
  firebase_database: ^10.2.0
  cloud_firestore: ^4.7.0
  marquee: ^2.2.3
  syncfusion_flutter_calendar: ^23.1.42
  calendar_view: ^1.0.0
  qr_code_scanner: ^1.0.1
  flutter_widget_from_html_core: ^0.10.0
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.9
  another_flushbar: ^1.12.30
  flutter_animate: ^4.2.0+1
  google_maps_flutter: ^2.5.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_rating_bar: ^4.0.1
  dots_indicator: ^3.0.0
  smooth_page_indicator: ^1.1.0
  hover: ^0.4.0
  anim_search_bar: ^2.0.3
  pluto_menu_bar: ^3.0.1
  animated_text_kit: ^4.2.2
  video_player: ^2.8.2
  chewie: ^1.0.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  build_runner: ^2.3.3

flutter: 
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/logo/
    - assets/images/breaking-news-slider/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Light.ttf
      
    - family: Dosis
      fonts:
        - asset: assets/fonts/Dosis-Bold.ttf
        - asset: assets/fonts/Dosis-ExtraBold.ttf
        - asset: assets/fonts/Dosis-SemiBold.ttf
        - asset: assets/fonts/Dosis-Medium.ttf
        - asset: assets/fonts/Dosis-Regular.ttf
        - asset: assets/fonts/Dosis-Light.ttf

