// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqDdjqax6Im3UPkxQoiipOQ2EhOCqIcBQ',
    appId: '1:50019849171:web:cc724d3acdd001315cd526',
    messagingSenderId: '50019849171',
    projectId: 'eboss-ba9bd',
    authDomain: 'eboss-ba9bd.firebaseapp.com',
    databaseURL: 'https://eboss-ba9bd.firebaseio.com',
    storageBucket: 'eboss-ba9bd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAASj-UNqgt6XncXFbm8-XwPehM2rYVV4o',
    appId: '1:50019849171:android:c9d4de3863a20ede5cd526',
    messagingSenderId: '50019849171',
    projectId: 'eboss-ba9bd',
    databaseURL: 'https://eboss-ba9bd.firebaseio.com',
    storageBucket: 'eboss-ba9bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU2oTcCdpebTrlR7rjypZs1jWD5p_74K0',
    appId: '1:50019849171:ios:ca492968aec4d8865cd526',
    messagingSenderId: '50019849171',
    projectId: 'eboss-ba9bd',
    databaseURL: 'https://eboss-ba9bd.firebaseio.com',
    storageBucket: 'eboss-ba9bd.appspot.com',
    androidClientId: '50019849171-14dp0p91f0qub6omo4e83v26q44cvqtr.apps.googleusercontent.com',
    iosBundleId: 'com.awfatech.ebosspromax',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU2oTcCdpebTrlR7rjypZs1jWD5p_74K0',
    appId: '1:50019849171:ios:ca492968aec4d8865cd526',
    messagingSenderId: '50019849171',
    projectId: 'eboss-ba9bd',
    databaseURL: 'https://eboss-ba9bd.firebaseio.com',
    storageBucket: 'eboss-ba9bd.appspot.com',
    androidClientId: '50019849171-14dp0p91f0qub6omo4e83v26q44cvqtr.apps.googleusercontent.com',
    iosBundleId: 'com.awfatech.ebosspromax',
  );
}
